language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- python setup.py install
- pip install strip-hints
- pip install -r test-requirements.txt
jobs:
  include:
  - stage: prep
    name: strip_type_hints
    script: python .travis/strip-type-hints.py
  - stage: test
    name: static_type
    script: nox -s static_type
  - stage: test
    name: pytests
    script: nox -s pytests
  - stage: test
    name: coverage
    script: coverage run --source ascii_canvas -m pytest ./tests --cov=ascii_canvas --cov-report=xml
      --cov-report=term

after_success:
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  user: Anton-4
  password:
    secure: ZIeVakvSeDwoQhiGyMPx1CJGhk/RoOrAkopysX3v3bDTnsDmEynsmXkkfd4GpJif+w0jZNWIqwwCE5ycioeReNtNhe18Ii9vzpxAIOeTNnfXqld16Zi9QH6nydWISb+LjAV23xafi35Rp6ahteSE7LqYu9b6yEaxdjZOsUTukVMni/Kpy4SDGyk7vL/jnIxzLVJfBW6DVJCGeGEno1ioqgkvBzoCl1W+xNKgE8g1Bqnmup/8Q0MyqG5rr+Gs1UkPVt9G+1xiTbp3KKUiz1XtIIeJKiXwBvutqWBP0qESeIFfrEE5Xx08oW+QW6wpEDKiuLrZpUClwrzCQa2Ru6RcZB1Sua+6t+DIjl40E2MZTC/USBd29iN3akp4vC1GSjne/leHCcwwitev2O4tvmhNfh0gMXjHWSR8b0A/AD3ySz95XsoMz6YY3c/zPWM5wclJexw0GU8LmUg5MOr+oD93rDyEL/htNVq0xUlrQELAexj4Y6vI8p/yFOej9gSJHMlfkXoOfpY/dzmH7uyWC5qfE1D2K0fc5qpx6zyzw6avDM9m1gdNihWXqxjYxeOmmuD1wQXRg6cNAPeSHLLriiurIpZ3mclRvW/FqDZOGFQCrMidOwJB0Atg1GfnP3qTOs33jYnxtzTVqaJmsukV6FqJa6WDiNGi5OJ9D4Xt5+M4ou0=
  on:
    tags: true
    repo: PaulSchweizer/ascii-canvas
    branch: master
    python: '3.6'
